### PR TITLE
added theme-status-indicator

### PR DESCRIPTION
**Pull request by prateekpranveer**
I have added an animated current-theme-status-indicator.

### CODE REVIEW

**Comment by fineanmol** [comment]
@prateekpranveer Thank you for the contribution, but to make this change you have changed all the color combination of the themes. 
Please don't change that, Just adding the theme indicator would be fine.

**Comment by prateekpranveer** [comment]
I intentionally changed the theme colors, I will stick to previous if those were fine. Don't worry!

**Comment by prateekpranveer** [comment]
Btw if you don't mind, can you mark this as hactober-accepted 🙃

**Comment by fineanmol** [comment]
> 

Yes Please @prateekpranveer . Make the necessary changes, and will be happy to merge your request 👍🏻

**Pull request closed without merging**
